<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE animales [
  <!ELEMENT animales (animal*)>
  <!ELEMENT animal (#PCDATA)>
]>

<animales>
  <animal>perro</animal>
  <animal>Caniche</animal>
  <animal>gato</animal>
  <animal>Siamés</animal>
</animales>