=== alemolamg/lenguajeMarcas1DAW/XSD-Ejercicios/examenesRepaso/resoluciónExamenA/examenA.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="tiendaMascotas" type="tipoMascotas"/>
  
  <!-- 
   -->
  <xs:complexType name="tipoMascotas">
  	<xs:sequence>
  		<xs:element name="reptiles" type="tipoReptiles"/>
  		<xs:element name="mamiferos" type="tipoMamiferos"/>
  		<xs:element name="unidadesMedida" type="tipoListaUnidadesMedida"/>
  		<xs:element name="direccion" type="tipoDireccion"/>
  		<xs:element name="clientes" type="tipoClientes"/>
  	</xs:sequence>
  	<xs:attribute name="nombre" type="xs:string"/>
  </xs:complexType>
  
  
  <!-- 
   -->
  <xs:complexType name="tipoReptiles">
  	<xs:sequence>
  		<xs:element name="reptil" maxOccurs="unbounded" type="tipoReptil"/>
  	</xs:sequence>
  </xs:complexType>

  
  <!-- 
  -->
  <xs:complexType name="tipoReptil" mixed="true">
  	<xs:all>
  		<xs:element name="peso" minOccurs="0" type="tipoMixtoConAtributoUnidadMedidaPeso"/>
  		<xs:element name="longitud" minOccurs="0" type="tipoMixtoConAtributoUnidadMedidaLongitud"/>
  		<xs:element name="edad" minOccurs="0" type="tipoMixtoConAtributoUnidadMedida"/>
  	</xs:all>
  </xs:complexType>


  <!-- 
   -->
  <xs:complexType name="tipoMixtoConAtributoUnidadMedida" mixed="true">
	<xs:attribute name="unidadMedida" type="tipoUnidadesMedidaTodas"/>
  </xs:complexType>

  <!--
  -->
  <xs:complexType name="tipoMixtoConAtributoUnidadMedidaLongitud">
     <xs:simpleContent>
        <xs:extension base="tipoNumerico1-800">
          <xs:attribute name="unidadMedida" type="tipoUnidadesMedidaTodas" />
        </xs:extension>
     </xs:simpleContent>
  </xs:complexType>

  <!--
  -->
  <xs:complexType name="tipoMixtoConAtributoUnidadMedidaPeso">
     <xs:simpleContent>
        <xs:extension base="tipoNumerico1-200">
          <xs:attribute name="unidadMedida" type="tipoUnidadesMedidaTodas" />
        </xs:extension>
     </xs:simpleContent>
  </xs:complexType>

   
  <!--
  --> 
  <xs:simpleType name="tipoNumerico1-800">
  	<xs:restriction base="xs:integer">
  		<xs:minInclusive value="1"/>
  		<xs:maxInclusive value="800"/>
  	</xs:restriction>
  </xs:simpleType>   
  
  <!--
  --> 
  <xs:simpleType name="tipoNumerico1-200">
  	<xs:restriction base="tipoNumerico1-800">
  		<xs:minInclusive value="1"/>
  		<xs:maxInclusive value="200"/>
  	</xs:restriction>
  </xs:simpleType>   
  
  <!-- 
  --> 
  <xs:complexType name="tipoMamiferos">
  	<xs:sequence>
  		<xs:element name="mamifero" maxOccurs="unbounded" type="tipoMamifero"/>
  	</xs:sequence>
  </xs:complexType>

  
  <!-- 
  -->
  <xs:complexType name="tipoMamifero">
  	<xs:sequence>
  		<xs:element name="nombre" type="tipoNombreMamifero"/>
  		<xs:element name="raza" type="tipoRazaMamifero"/>
  		<xs:element name="descripcion" type="xs:string"/>  	
  	</xs:sequence>
  	<xs:attribute name="codigo">
  		<xs:simpleType>
  			<xs:restriction base="xs:string">
  				<xs:pattern value="[A-Z]{3}-[(][0-9]{5}[)]"/>
  			</xs:restriction>
  		</xs:simpleType>
  	</xs:attribute>
  </xs:complexType> 
   
   
  <!-- 
  -->
  <xs:complexType name="tipoNombreMamifero">
  	<xs:attribute name="valor">
  		<xs:simpleType>
  			<xs:restriction base="xs:string">
  				<xs:pattern value=".+"/>
  			</xs:restriction>
  		</xs:simpleType>
  	</xs:attribute>
  </xs:complexType> 
  
  
  <!-- 
  -->
  <xs:complexType name="tipoRazaMamifero">
  	<xs:choice>
  		<xs:element name="perro" type="tipoVacio"/>
  		<xs:element name="orca" type="tipoVacio"/>
  		<xs:element name="delfin" type="tipoVacio"/>
  	</xs:choice>
  </xs:complexType>
   
   
  <!--
  -->
  <xs:complexType name="tipoVacio"/> 
  
  
  <!-- 
  -->
  <xs:simpleType name="unidadesMedidaLongitudPeso">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="mm"/>
  		<xs:enumeration value="cm"/>
  		<xs:enumeration value="dm"/>
  		<xs:enumeration value="m"/>
  		<xs:enumeration value="kg"/>
  		<xs:enumeration value="Kg"/>
  	</xs:restriction>
  </xs:simpleType>
  
  <!-- 
  -->
  <xs:simpleType name="unidadesMedidaTiempo">
  	<xs:restriction base="xs:string">
  		<xs:enumeration value="dias"/>
  		<xs:enumeration value="semanas"/>
  		<xs:enumeration value="meses"/>
  	</xs:restriction>
  </xs:simpleType>
  
  
  <!-- 
  -->
  <xs:simpleType name="tipoUnidadesMedidaTodas">
  	<xs:union memberTypes="unidadesMedidaLongitudPeso unidadesMedidaTiempo"/>
  </xs:simpleType>
  
  <!-- 
  -->
  <xs:simpleType name="tipoListaUnidadesMedida">
  	<xs:list itemType="tipoUnidadesMedidaTodas"/>
  </xs:simpleType>
 
 
  <!-- 
  -->
  <xs:complexType name="tipoDireccion">
  	<xs:sequence>
  		<xs:element name="postal" type="xs:string"/>
  		<xs:element name="telefono" type="xs:string"/>
  	</xs:sequence>
  </xs:complexType>
  
  
  <!-- 
   -->
  <xs:complexType name="tipoClientes">
  	<xs:sequence>
  		<xs:element name="cliente" maxOccurs="unbounded" type="tipoCliente"/>
  	</xs:sequence>
  </xs:complexType>
  
  <!-- 
   -->
  <xs:complexType name="tipoCliente">
    <xs:complexContent>
      <xs:extension base="tipoDireccion">
        <xs:sequence>
          <xs:element name="email" type="xs:string" />
        </xs:sequence>
        <xs:attribute name="nombre" type="xs:string"/>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
</xs:schema>

=== alemolamg/lenguajeMarcas1DAW/XSD-Ejercicios/examenesRepaso/resoluciónExamenA/Examen_A_Mascotas.xml
<?xml version="1.0" encoding="UTF-8"?>
<tiendaMascotas nombre="Mascotas Villalba, S.A." xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="examenA.xsd">
	<reptiles>
 		<reptil>Boa constrictor
			<peso unidadMedida="Kg">65</peso>
			<longitud unidadMedida="cm">230</longitud>
			<edad unidadMedida="meses">14</edad>
		</reptil>
		<reptil>Iguana
			<peso unidadMedida="Kg">2</peso>
			<longitud unidadMedida="mm">500</longitud>
		</reptil>
	</reptiles>
	<mamiferos>
 		<mamifero codigo="ABC-(12345)">
			<nombre valor="Toby"/>
			<raza>
				<perro/>
			</raza>
			<descripcion>Un perro precioso</descripcion>
		</mamifero>
		<mamifero codigo="ZYX-(98765)">
			<nombre valor="Willy"/>
			<raza>
				<orca/>
			</raza>
			<descripcion>Es una orca muy graciosa</descripcion>
		</mamifero>
		<mamifero codigo="GHI-(55567)">
			<nombre valor="Flipper"/>
			<raza>
				<delfin/>
			</raza>
			<descripcion>De película</descripcion>
		</mamifero>
	</mamiferos>
	<unidadesMedida>mm cm dm m kg dias semanas meses</unidadesMedida>
	<direccion>
		<postal>Calle del Pez, 56 - 14900 - Lucena</postal>
		<telefono>654123987</telefono>
	</direccion>
	<clientes>  
		<cliente nombre="Rafalillo">
			<postal>Calle del acuario, 33, 3º-D - 14900 - Lucena</postal>
			<telefono>621465987</telefono>
			<email>rafalillo@gmail.com</email>
		</cliente> 
	</clientes>
</tiendaMascotas>
