=== alemolamg/lenguajeMarcas1DAW/ejercicios-Con-Errores/ejercicios/01_ordenadores.dtd
<!ELEMENT placasBase (placaBase+)>
<!ELEMENT placaBase (microprocesador, memoria, modelo, fabricante)>
<!ELEMENT microprocesador (#PCDATA)>
<!ELEMENT memoria (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT fabricante ((Intel | Asus))>
<!ELEMENT Intel EMPTY>
<!ELEMENT Asus EMPTY>

=== alemolamg/lenguajeMarcas1DAW/ejercicios-DTD/ejercicios/01_ordenadores.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE placasBase SYSTEM "01_ordenadores.dtd">
<placasBase>
	<placaBase>
		<microprocesador>Radeon 787534EU</microprocesador>
		<memoria>32GB</memoria>
		<modelo>AMD 25896TXR</modelo>
		<fabricante><Asus/></fabricante>
	</placaBase>
	<placaBase>
		<microprocesador>Radeon 8552</microprocesador>
		<memoria>64GB</memoria>
		<modelo>AMD 25878TXR-Sup</modelo>
		<fabricante><Intel/></fabricante>
	</placaBase>
</placasBase>
