=== alemolamg/lenguajeMarcas1DAW/ejercicios-Con-Errores/ejercicios/02_correosElectronicos.dtd
<!ELEMENT emails (email*)>
<!ELEMENT email (para*, cc*, cco*, asunto, cuerpo, adjunto*)>
<!ELEMENT para (#PCDATA)>
<!ELEMENT cc (#PCDATA)>
<!ELEMENT cco (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT cuerpo (#PCDATA)>
<!ELEMENT adjunto (nombre, mime-type, longitud)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT mime-type (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>

=== alemolamg/lenguajeMarcas1DAW/ejercicios-DTD/ejercicios/02_correosElectronicos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE emails SYSTEM "02_correosElectronicos.dtd">
<emails>
	<email>
		<para>rafa@gmail.com</para>
		<cc>Juan@gmail.com</cc>
		<cco>Pablo@gmail.com</cco>
		<asunto>Holaaaa, qu√© tal????</asunto>
		<cuerpo>Me alegro de escribirte.....</cuerpo>
		<adjunto>
			<nombre>Nosotros_en_Malaga.jpg</nombre>
			<mime-type>image/jpeg</mime-type>
			<longitud>8596KB</longitud>
		</adjunto>
	</email>
</emails>
